steps:
  # Buildpackを使用してビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--rm', '-v', '/workspace:/workspace', '-w', '/workspace', 'gcr.io/buildpacks/builder:v1', 'pack', 'build', 'gcr.io/$PROJECT_ID/survey-app:$COMMIT_SHA', '--builder', 'gcr.io/buildpacks/builder:v1', '--env', 'NODE_ENV=production', '--env', 'NPM_CONFIG_PRODUCTION=false', '--no-pull']

  # イメージをContainer Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/survey-app:$COMMIT_SHA']

  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'survey-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/survey-app:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/survey-app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY 